hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('chart', views.chart, name="chart"),
]

new/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hello.urls')),
]

hello/models.py
from django.db import models
import pandas as pd
import joblib
# Create your models here.


class IrisPlants(models.Model):
    length_petal = models.FloatField()
    length_sepal = models.FloatField()
    width_petal = models.FloatField()
    width_sepal = models.FloatField()
    species = models.IntegerField(
        choices=((0, "Setosa"), (1, "Versicolor"), (2, "Virginica"),))

hello/views.py
from django.shortcuts import render, redirect
import pandas as pd
# import matplotlib.pyplot as plt
import numpy as np
import json
from .models import IrisPlants
import pickle
import joblib

# Create your views here.


def home(request):
    if request.method == 'POST':

        length_petal = request.POST['petal_length']
        length_sepal = request.POST['sepal_length']
        width_petal = request.POST['petal_width']
        width_sepal = request.POST['sepal_width']

        file1 = open('hello/iris_pkl_1.pkl', 'rb')
        loaded_model = joblib.load(file1)

        species = loaded_model.predict(
            [[length_sepal, width_sepal, length_petal, width_petal]])[0]

        iris_instance = IrisPlants.objects.create(
            length_petal=length_petal, length_sepal=length_sepal, width_petal=width_petal, width_sepal=width_sepal, species=species)

        return render(request, 'home.html', {"iris": iris_instance})

    else:
        return render(request, 'home.html')


def chart(request):
    iris = pd.read_csv("iris.csv")
    print(iris.shape)
    sepal_lengths = iris['sepal_length']
    sepal_widths = iris['sepal_width']

    lists = []
    for i in range(len(sepal_lengths)):
        lists.append([sepal_lengths[i], sepal_widths[i]])

    setosa = list()
    virginica = list()
    versicolor = list()

    setosa_num = 0
    versicolor_num = 0
    virginica_num = 0

    for i in range(len(iris['species'])):
        if ((iris['species'][i]) == 'setosa'):
            setosa_num += 1
        if ((iris['species'][i]) == 'versicolor'):
            versicolor_num = versicolor_num + 1
        if ((iris['species'][i]) == 'virginica'):
            virginica_num = virginica_num + 1

    setosa.append(setosa_num)
    versicolor.append(versicolor_num)
    virginica.append(virginica_num)

    categories = list()
    categories.append('species')

    return render(request, 'chart.html', {
        'categories': json.dumps(categories),
        'setosa': json.dumps(setosa),
        'virginica': json.dumps(virginica),
        'versicolor': json.dumps(versicolor)})

templates/chart.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <title>Django Highcharts Example</title>
</head>

<body>
    <h1>welcome</h1>
    <div id="container"></div>
    <script src="https://code.highcharts.com/highcharts.src.js"></script>
    <script>
        Highcharts.chart('container', {
            chart: {
                type: 'column'
            },
            title: {
                text: 'Titanic Survivors by Ticket Class'
            },
            xAxis: {
                categories: {{ categories| safe }}
      },
            series: [{
                name: 'setosa',
                data: {{ setosa }},
            color: 'green'
      }, {
                name: 'versicolor',
                data: {{ versicolor }},
            color: 'red'
      }, {
                name: 'virginica',
                data: {{ virginica }},
            color: 'blue'
        }]
  });
    </script>
</body>

</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="style.css">
    <title>Home</title>
</head>

<body>
    <h1>This is homepage</h1>

    <form action="{% url 'home' %}" method="POST">
        {% csrf_token %}
        <label for="sepal_length">Sepal Length : </label>
        <input type="number" id="sepal_length" step="0.01" name="sepal_length" required><br><br>
        <label for="petal_length">Petal Length : </label>
        <input type="number" id="petal_length" step="0.01" name="petal_length" required><br><br>
        <label for="sepal_width">Sepal Width : </label>
        <input type="number" id="sepal_width" step="0.01" name="sepal_width" required><br><br>
        <label for="petal_width">Petal Width : </label>
        <input type="number" id="petal_width" step="0.01" name="petal_width" required><br><br>
        <button type=" submit">Predict</button>
    </form>
    <!-- {% if iris.get_species_display %} -->

    <h2>Iris <mark>{{ iris.get_species_display }}</mark> Species</h2>

    <!-- {% endif %} -->

</body>

</html>

templates/home1.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load('current', { 'packages': ['corechart'] });
        google.charts.setOnLoadCallback(drawChart);
        function drawChart() {
            var data = google.visualization.arrayToDataTable([
                ['Petal_Length', 'Petal_Width'],
                [5, 7],
                [6, 9]
            ]);

            var options = {
                title: 'Petal Length VS Petal Width',
                hAxis: { title: 'length', minValue: 0, maxValue: 15 },
                vAxis: { title: 'width', minValue: 0, maxValue: 15 },
                legend: { position: 'top', textStyle: { color: 'blue', fontSize: 16 } }
            };

            var chart = new google.visualization.ScatterChart(document.getElementById('chart_div'));

            chart.draw(data, options);
        }
    </script>


    <title>GRaphS</title>
</head>

<body>
    <h1>Welcome</h1>

    <div id="chart_div" style="width: 900px; height: 500px;"></div>

    <h4>The shape of iris dataset is {{ iris.shape }}</h4>
    <h4>The Columns in iris dataset are {{ iris.columns }}</h4>
    <h4>The number of Species in iris dataset are : </h4> {{ value_counts}} <br>

    {% for length in sepal_length %}
    {{ length }}
    {% endfor %} <br>

    {% for width in sepal_width %}
    {{ width }}
    {% endfor %}








    <script src="https://code.highcharts.com/highcharts.src.js"></script>
</body>

</html>

< !--categories: ['Africa', 'America' , 'Asia' , 'Europe' , 'Oceania' ]-->